org: m0jjmd
app: dashboard-api
service: dashboard-mongo-api
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  stage: production
  timeout: 30
  logs:
    restApi: true
  environment:
    NODE_ENV: lambda

functions:
  app:
    handler: dist/lambda.handler  
    events:
      - http: ANY /api
      - http: ANY /api/{proxy+}